# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dependency injection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dependency injection

  target 'Dependency injectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dependency injectionUITests' do
    # Pods for testing
  end

end
